package com.hims.constants;

public enum NotificationType {
    OTHER_APPOINTMENT_BOOKED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,

    INVOICE_GENERATED,

    PATIENT_REGISTERED,

    PAYMENT_SUCCESS,
    PAYMENT_FAILED,

    REFUND_INITIATED,
    REFUND_COMPLETED
}